language: node_js
node_js:
- 5.5.0
before_install:
- npm install
sudo: false
before_deploy:
- npm-prepublish --verbose
deploy:
- provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  on:
    tags: true
env:
  global:
  # NPM_EMAIL
  - secure: "S5ZZFtm1KFbrN/BkfBR2lkBlqFu0lQrzXfnGimiv0sbmeqMY62hOHh0DiKfrvqhImSIeufR7QHdDKHMqr3JQowdUMU5I8h45dW0ZFWKnbm/Ac8jMUJIeboDm/aTMeoJwdLdIhBOyV9fJlN/GTeCEUUFpF2Uh2RhuKqpdBlYyFjrcAYgJvj68zcPMXXIq/cs6ouEX0Fn+HCRPndOC07VlJHLYHWo0Blv9C9TQ3ncfuryiZxgwqSOFVn49522OjmEd2Fh8+MXXJXhWq14yUL0JiURo4iQBUnm2KfYiuJyMUCYalWZq+BMq1KK+G5l18OJeaKJF1SzXDON38nOqUjBKqi5maEBcG16HIIREQFx3yiXwLS8vuv0bOYMnk9qsjo8o98evp+N0xpmMo6mOe0X/qFFJtIgbDL1g6BKRc9YwzcWLP1Tc3KOKQVkHQDWth+/vzN27eSgbpvYFOtVm0AVEjxUne9PNvit72uhHz9iisYLO5OQS9Jdj8B3i80+Pp75BVZ+Bow4m3pVXUqngycklFjTjUKRNCXxQD+WvpllBytCzBgt7STGAm6oBNfal9l40UX3vzcwmRhxHD+Ik1XFo6prfEv8Qlt549zO1x3L358zQ3vc8UUFLuVIUNSjmm1NHXTZJm3hSiMOtzWcYAycMb4GFqvB62PD8O3GzQb7EyH4="
  # NPM_API_KEY
  - secure: "cODmtbLuewwwd7mBvG0UPO1gETecun2VEffI3+aOfSoWqJ3XjN1pfgGzqPj9hEfQnLcih5uQRAG00n04v8bkuicvCDWX2L1lQge61ShNs3WJam30c9FLt6pKolh0hIOZxUC9rifrkfOFT/AQ0xraB8lLyK6geqHKQSf3KTsVMIpzq1+i5hytrFd5OIzJ2ZaMU7fQdrC5WdNalrGtHqy3vcA2+evfIgsKZ5W0aYYq+0j9j7VXCdqlA0WRZIK3+b3uhQLFG8XanvIwY40poX0+I0CXokNPX0DKy/1gYpaIQFbegEeGkn6/3NfsM4XGedIViOCFuot98QkQyuesnsDkQhs+dBGbM2/G+Ah1h762GLnsgMqtcR9QR2Ne+hKb6mAmzouhToYJFA88Bnh/uzcXhf3U+nILoDvKL7413qAGZ1qux5DghYwREytcjI448PjTLHR6JbzUUMqtSmxzw9un4NytIIqLk/FaBIRzBlo/+NLltiMFGGoRmjSyHLXQRgOu70Lo2VYaZPHr4f73AUHqIB0ZzN0DZJiX2V0/y2vN4blK0Oz8wevrfAygfiulEVLPpjNAapovOHof6zAr6LVgrjl6mVmn2T9UwBWm65U4uwzOHNRQlSMWC8ICGkRk+992zMEbryff6Vub8C65D/Q8yn9MSkvSDIo0Ea0hMhbqAIY="
