language: node_js
node_js:
- 5.2.0
install:
- npm install
script:
- webpack
sudo: false
env:
  global:
  - secure: l7lh0SwAqtjPm+b9d1klW6K55pqPmOm1c8HEOc5ARv57Jedg1CZfTUK6hHGvHyY+68ygfP3003jhF0BwRdcnJTSlZyNHIrHmxNipeBu9EapC+j14zHjR72q9PqzPpnbIv1Cy04dwH+QNeeEJ6nJMzpoonoAX8VSq0Np47UtiApMKbbSyesah0XmmEWFt6uSabMSdn1+nWbp4jLL2Lz41+q3QOCdCGX6LyD9LuLHlbSs8Cu1YRCEcaCQikmfKuOkVe7A++EQswSpnFAewzB7gCf5n43Po7Nke61lE28/h9SaZlr0YqbGxN+pZsNZu+vigdAQzLLPDDP+TurbDeJ2+TROPbLf2/3BSA/gzPsSY95Qr3cBSniY3DRE8I/lWk43RQ4vSJuyVCpZ+p0QU7ra9bNnicwi29ZORrnIvvr33OYvZIhboHkT6PnkN6GSdSPfk0o1sNNEhJX2vNnDxsopGZXmGDUC6szsAnnxz/huxCQ4VhHF3RrJgqqWYSBwq6UxN2L0UhyeoPnS9z/HglE5PfLO3mbgterDtxucUlvGXHILPgRK3HH++tZLdZ5AY9GeNp59HPkUQARnsUGupiC4uitqfn95w9Fu3HHnjzTgHl8f94uhpjtbPGC8xdYWnPDVkU08CstAnIzR0OcZkIQvYIswknooNBHdoJO8mmD9nQy0=
  - secure: E1t0Ui2ynKQGKOH6gLYtDEWPLsNFzQkN4QyoCaQDyfz3UX0jMgRDI8UrVHVJkBjsv2dRALFBOypmAXd4iEMLDiu9T+Su3pUbu7R760Tv7P45PeYQ9kbIJvlVcQX9vvZ0oEpSXChthiP31jbJUDEHGmK8q1h+HOJctPHzF/hZaOb1ZctPdk7mBpSfDVZjS6BRvSol2ihKxIVkDsnLWrMW7oRTfmHKgjWqxDJXbzGrpwFzVo+xp0dkTDNv4FJXNQCW+eDpYFBgfXnxfvLNEBJbhReHVlBrIMyBpBbxvrhUXdeetdtDvg8+rFtHu4S3jsuFz4J93kSEUt4Y4Xwi+2gv8RxGly5BgFFtSTIsantaFyN/k28NFE6sKRhAALPgZmqy8tGu5GpQys6sIoQ8OlFclkPCVCzRHZJ8vYs6kLM28czIX6W3UFWfBfNK/CCncJUnJ2lGXfc1cfAQJdgaF/0VbPlBos03cOZmmwMkL5h2S1bwsWkeT9wDI/fOefJ8UZtQVPYFKsI77+3F/HGk7tVrqe/YVmT12uZqFJLh3FFNmFubz55XNMfYZ1vtpn+OnIfRBAPsUCTXxCtHPgutpWBeQ4LRu9MuEb3GLxaMCoLQHJoV3KKsVHtiuVfXYgsMhLAXyVK2+tiFsInALxyNbHOc0TvKkonnzlHalVbeXWoO1Hs=
